In [9]:
# ee

In [10]:
!ls

2.5kmX2.5km_nhd_variables_extracted
2.5kmX2.5km_nhd_variables_extracted.csv
2.5kmX2.5km_nhd_variables_extracted_stripped
2.5kmX2.5km_nhd_variables_partsmerged
2.5kmX2.5km_nhd_variables_partsmerged_pk3.pkl
200mX200m_nhd_variables_extracted
200mX200m_nhd_variables_extracted.csv
200mX200m_nhd_variables_extracted_stripped
200mX200m_nhd_variables_partsmerged
200mX200m_nhd_variables_partsmerged_pk3.pkl
2021.03.09_NHD_extraction_from_pickled_files_v6-200m.ipynb
2021.03.09_NHD_extraction_from_pickled_files_v6.ipynb
2021.03.09_nhd_variables_extracted_from_2.5kmX2.5km.csv
2021.03.09_nhd_variables_extracted_from_2.5kmX2.5km_pkl3.pkl
2021.03.09_nhd_variables_extracted_from_200mX200m.csv
2021.03.09_nhd_variables_extracted_from_200mX200m_pkl3.pkl
2021.03.17_NHD_extraction_from_pickled_files_v7.ipynb
2021.03.17_NHD_extraction_from_pickled_files_v7_200m.ipynb
2021.03.22_1. Extract_NHD_Variables_nearest_wb_from_GEE.ipynb
2021.03.22_2. calculate_closest_centroid-Copy1.ipynb
2021.03.22_2. calculate_closest_centroid-Copy2.ipynb
2021.03.22_2. calculate_closest_centroid.ipynb
2021.03.22_NHD_nearest_wb.ipynb
2021.03.22_calculate_closest_centroid.ipynb
2021.03.23_3. nearest_wb_fl_distance_area_elevation.ipynb
calculating_centroid_for_nearest_bodies
combined_regular_clean_with_ssurgo_variables.csv
nearest_wb_fl_elevation
nhd_stats_AI.csv

In [18]:
import pandas as pd
import numpy as np
import time
import ee
import pickle
ee.Initialize()
!pip install geopy
from geopy import distance

coords_1 = (52.2296756, 21.0122287)
coords_2 = (52.406374, 16.9251681)

print (distance.distance(coords_1, coords_2).m)

Requirement already satisfied: geopy in /Users/Madhukar/opt/miniconda3/envs/ee/lib/python3.9/site-packages (2.1.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /Users/Madhukar/opt/miniconda3/envs/ee/lib/python3.9/site-packages (from geopy) (1.50)
279352.90160430095

In [20]:
# comid's from GEE are extracted into several pickled files
# pickling is needed to be able to share easily across team members 
# join these pickled files into one full dataset

df_centroid_list = []

for i in range(df_m.shape[0] // 500 + 1):
    try:
        df_temp = pd.read_pickle('calculating_centroid_for_nearest_bodies/NHD_extracted_vars_2500mX2500m_with_centroid_part' + str(500 * i + 1))
#         print(df_temp.columns)
        df_centroid_list.append(df_temp)
    except:
        break

df_centroid = pd.concat(df_centroid_list)

In [21]:
print(df_centroid.shape)
df_centroid.head()

(14619, 31)

,Unnamed: 0,Unnamed: 0.1,jurisdiction_type,da_number,district,project_name,longitude,latitude,date_issued_or_denied,rha_determination,...,cwa9,potential_wetland,index,Index,mukey,hydclprs,aws025wta,drclassdcd,nhd_vars_wb_centroid,nhd_vars_fl_centroid
0,0,0,RAPANOS,LRB-1983-10120,Buffalo,Trade-A-Yacht (Hibiscus Harbor - Union Springs...,-76.70773,42.85821,06/19/2020,0,...,0,1,1,1,289404.0,100.0,7.40,Very poorly drained,"([120052831, 22026970, 22026972, 22026962, 220...","([21979931, 21979911, 21979905, 21979901, 2197..."
1,1,1,RAPANOS,LRB-1985-69031,Buffalo,"POOLEY, MARK A.",-75.85524,43.15230,07/07/2016,0,...,0,0,2,2,293511.0,0.0,0.00,NaN,"([166766871], [[-75.90992647216409, 43.2034234...","([22023626, 22023590, 22024934, 22024936, 2202..."
2,2,2,RAPANOS,LRB-1986-99614,Buffalo,"Bellamy, Michael (previous: MACKO, JOHN)",-78.04046,42.68911,10/12/2017,0,...,0,0,3,3,295436.0,0.0,0.00,NaN,"([15548613], [[-78.03287556981176, 42.69405049...","([15549029, 15549021, 15549673, 15549671, 1554..."
3,3,3,RAPANOS,LRB-1990-97632,Buffalo,WESTWOOD COUNTRY CLUB,-78.77134,42.97994,06/28/2016,0,...,0,1,4,4,290780.0,5.0,2.25,Moderately well drained,"([15568189, 15568193], [[-78.77190145923849, 4...","([15569727, 15568933], [[-78.75975051198779, 4..."
4,4,4,RAPANOS,LRB-1991-98611,Buffalo,MODERN LANDFILL INCORPORATED,-78.97142,43.21616,03/22/2016,0,...,0,1,5,5,293019.0,93.0,5.20,Poorly drained,"([], [], [], [], [])","([15560517, 15560355, 15560297, 15560311, 1556..."

In [22]:
# read in the nhd addendum file
nhd_stats = pd.read_csv("nhd_stats_AI.csv")

# read in csv file with SSURGO variables
df_m = pd.read_csv("combined_regular_clean_with_ssurgo_variables.csv")

In [23]:
df_centroid.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'Index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb_centroid',
       'nhd_vars_fl_centroid'],
      dtype='object')

In [24]:
df_centroid.nhd_vars_wb_centroid[0]

([120052831, 22026970, 22026972, 22026962, 22026958, 22026964],
 [[-76.6822888614142, 42.701488423034924],
  [-76.70555483355493, 42.857404962517336],
  [-76.70557703121408, 42.85613558931026],
  [-76.7024219454243, 42.862812067268266],
  [-76.69901566135943, 42.86586459505723],
  [-76.69326825928754, 42.861572777915995]],
 ['974076', '', '', '', '', ''],
 [171.202, 0.006, 0.006, 0.015, 0.012, 0.008],
 [0, nan, nan, nan, nan, nan])

In [25]:
df_centroid.nhd_vars_wb_centroid[0][1]

[[-76.6822888614142, 42.701488423034924],
 [-76.70555483355493, 42.857404962517336],
 [-76.70557703121408, 42.85613558931026],
 [-76.7024219454243, 42.862812067268266],
 [-76.69901566135943, 42.86586459505723],
 [-76.69326825928754, 42.861572777915995]]

In [26]:
def wb_distance_list(x):
    try:
        return ([round(distance.distance((x.latitude, x.longitude), 
                                         (coord[1], coord[0])).km, 5) 
                 for coord in x.nhd_vars_wb_centroid[1]])
    except:
        return []
    
def fl_distance_list(x):
    try:
        return ([round(distance.distance((x.latitude, x.longitude), 
                                         (coord[1], coord[0])).km, 5) 
                 for coord in x.nhd_vars_fl_centroid[1]])
    except:
        return []
    
# df_centroid["wb_centroid_dist_list"] = (df_centroid.apply(lambda x: 
#                                                           [round(distance.distance((x.latitude, x.longitude), 
#                                                                                    (coord[1], coord[0])).km, 5) 
#                                                            for coord in x.nhd_vars_wb_centroid[1]], 
#                                                           axis=1))

df_centroid["wb_centroid_dist_list"] = (df_centroid.apply(lambda x: wb_distance_list(x), axis=1))
df_centroid["fl_centroid_dist_list"] = (df_centroid.apply(lambda x: fl_distance_list(x), axis=1))

In [27]:
df_centroid[["nhd_vars_wb_centroid", "wb_centroid_dist_list"]]

,nhd_vars_wb_centroid,wb_centroid_dist_list
0,"([120052831, 22026970, 22026972, 22026962, 220...","[17.53399, 0.199, 0.28994, 0.67049, 1.10918, 1..."
1,"([166766871], [[-75.90992647216409, 43.2034234...",[7.21302]
2,"([15548613], [[-78.03287556981176, 42.69405049...",[0.82916]
3,"([15568189, 15568193], [[-78.77190145923849, 4...","[1.03075, 0.78709]"
4,"([], [], [], [], [])",[]
...,...,...
14614,"([22850275], [[-92.09210850004088, 34.33071380...",[1.26976]
14615,"([], [], [], [], [])",[]
14616,"([832364, 832392], [[-95.54920237997074, 36.13...","[1.40828, 1.36894]"
14617,"([], [], [], [], [])",[]
14618,"([562027], [[-98.97695549214, 34.6351538500515...",[1.44951]

In [28]:
df_centroid.nhd_vars_wb_centroid[0]

([120052831, 22026970, 22026972, 22026962, 22026958, 22026964],
 [[-76.6822888614142, 42.701488423034924],
  [-76.70555483355493, 42.857404962517336],
  [-76.70557703121408, 42.85613558931026],
  [-76.7024219454243, 42.862812067268266],
  [-76.69901566135943, 42.86586459505723],
  [-76.69326825928754, 42.861572777915995]],
 ['974076', '', '', '', '', ''],
 [171.202, 0.006, 0.006, 0.015, 0.012, 0.008],
 [0, nan, nan, nan, nan, nan])

In [29]:
def wb_min_index(x):
    try:
        return int(x.wb_centroid_dist_list.index(min(x.wb_centroid_dist_list)))
    except:
        return np.nan
    
def fl_min_index(x):
    try:
        return int(x.fl_centroid_dist_list.index(min(x.fl_centroid_dist_list)))
    except:
        return np.nan

df_centroid["wb_min_index"] = df_centroid.apply(lambda x: wb_min_index(x), axis=1)
df_centroid["fl_min_index"] = df_centroid.apply(lambda x: fl_min_index(x), axis=1)

In [30]:
def closest_wb_distance(x):
    try:
        return x.wb_centroid_dist_list[int(x.wb_min_index)]
    except:
        return np.nan

def closest_fl_distance(x):
    try:
        return x.fl_centroid_dist_list[int(x.fl_min_index)]
    except:
        return np.nan
    
df_centroid["closest_wb_distance_m"] = df_centroid.apply(lambda x: closest_wb_distance(x), axis=1)
df_centroid["closest_fl_distance_m"] = df_centroid.apply(lambda x: closest_fl_distance(x), axis=1)

In [31]:
def closest_wb_area(x):
    try:
        return x.nhd_vars_wb_centroid[3][int(x.wb_min_index)]
    except:
        return np.nan


# fl coord need to be extracted from nhd_stats
# so need one additional function
    
def extract_feature(comid, feature):
    """
    Extract features present in nhd_stats for corresponding comid
    """
    if comid == None:
        return np.nan # if no comid's in GEE
    extracted_feature = nhd_stats[nhd_stats["comid"] == comid][str(feature)]
    try:
        extracted_feature = np.array(extracted_feature).item() 
    except Exception as e:
        return np.nan # if comid in GEE but not in nhd database
    return extracted_feature
    
    
def closest_fl_area(x):
    try:
        return extract_feature(x.nhd_vars_fl_centroid[0][int(x.fl_min_index)], "areasqkm")
    except:
        return np.nan
    
df_centroid["closest_wb_area_sqkm"] = df_centroid.apply(lambda x: closest_wb_area(x), axis=1)
df_centroid["closest_fl_area_sqkm"] = df_centroid.apply(lambda x: closest_fl_area(x), axis=1)

In [32]:
df_centroid["closest_fl_area_sqkm"]#[15:21]

0         0.1170
1         1.4841
2         1.1124
3        13.9392
4         0.4644
          ...
14614     0.8316
14615     5.5170
14616    13.1337
14617     0.7866
14618     3.6135
Name: closest_fl_area_sqkm, Length: 14619, dtype: float64

In [33]:
def closest_wb_centroid(x):
    try:
        return x.nhd_vars_wb_centroid[1][int(x.wb_min_index)]
    except:
        return np.nan

def closest_fl_centroid(x):
    try:
        return x.nhd_vars_fl_centroid[1][int(x.fl_min_index)]
    except:
        return np.nan
    
df_centroid["closest_wb_centroid_coord"] = df_centroid.apply(lambda x: closest_wb_centroid(x), axis=1)
df_centroid["closest_fl_centroid_coord"] = df_centroid.apply(lambda x: closest_fl_centroid(x), axis=1)

In [34]:
df_centroid.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'Index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb_centroid',
       'nhd_vars_fl_centroid', 'wb_centroid_dist_list',
       'fl_centroid_dist_list', 'wb_min_index', 'fl_min_index',
       'closest_wb_distance_m', 'closest_fl_distance_m',
       'closest_wb_area_sqkm', 'closest_fl_area_sqkm',
       'closest_wb_centroid_coord', 'closest_fl_centroid_coord'],
      dtype='object')

In [35]:
df_centroid.closest_fl_centroid_coord

0        [-76.72068711614911, 42.847915233402816]
1          [-75.8611681181417, 43.15253659471059]
2         [-78.03825316195692, 42.68513894536421]
3        [-78.75975051198779, 42.984037710099216]
4         [-78.96400638899155, 43.21088023895628]
                           ...
14614     [-92.09799233523734, 34.33076202423372]
14615    [-92.63946712914063, 35.900102466803624]
14616      [-95.5603482061016, 36.14571290965774]
14617     [-97.58076374775679, 35.65157215755072]
14618    [-98.98107367499516, 34.620999433833575]
Name: closest_fl_centroid_coord, Length: 14619, dtype: object

In [36]:
# save this file
# has the critical centroid coords, distance, area but not elevation which needs GEE below
(pickle.dump(df_centroid, open("nearest_wb_fl_elevation/nearest_wb_fl_elevation_raw","wb"), 
               protocol=3))          
pd.read_pickle("nearest_wb_fl_elevation/nearest_wb_fl_elevation_raw")

,Unnamed: 0,Unnamed: 0.1,jurisdiction_type,da_number,district,project_name,longitude,latitude,date_issued_or_denied,rha_determination,...,wb_centroid_dist_list,fl_centroid_dist_list,wb_min_index,fl_min_index,closest_wb_distance_m,closest_fl_distance_m,closest_wb_area_sqkm,closest_fl_area_sqkm,closest_wb_centroid_coord,closest_fl_centroid_coord
0,0,0,RAPANOS,LRB-1983-10120,Buffalo,Trade-A-Yacht (Hibiscus Harbor - Union Springs...,-76.70773,42.85821,06/19/2020,0,...,"[17.53399, 0.199, 0.28994, 0.67049, 1.10918, 1...","[2.40717, 1.58126, 1.64269, 1.55869, 1.60175, ...",1.0,3.0,0.19900,1.55869,0.006,0.1170,"[-76.70555483355493, 42.857404962517336]","[-76.72068711614911, 42.847915233402816]"
1,1,1,RAPANOS,LRB-1985-69031,Buffalo,"POOLEY, MARK A.",-75.85524,43.15230,07/07/2016,0,...,[7.21302],"[1.73769, 0.91706, 2.41943, 0.4829, 0.78528]",0.0,3.0,7.21302,0.48290,207.005,1.4841,"[-75.90992647216409, 43.20342341684462]","[-75.8611681181417, 43.15253659471059]"
2,2,2,RAPANOS,LRB-1986-99614,Buffalo,"Bellamy, Michael (previous: MACKO, JOHN)",-78.04046,42.68911,10/12/2017,0,...,[0.82916],"[1.68334, 1.49511, 1.20173, 0.91498, 0.47677, ...",0.0,4.0,0.82916,0.47677,3.329,1.1124,"[-78.03287556981176, 42.694050497478464]","[-78.03825316195692, 42.68513894536421]"
3,3,3,RAPANOS,LRB-1990-97632,Buffalo,WESTWOOD COUNTRY CLUB,-78.77134,42.97994,06/28/2016,0,...,"[1.03075, 0.78709]","[1.04919, 1.52478]",1.0,0.0,0.78709,1.04919,0.004,13.9392,"[-78.77438291804144, 42.986663531552246]","[-78.75975051198779, 42.984037710099216]"
4,4,4,RAPANOS,LRB-1991-98611,Buffalo,MODERN LANDFILL INCORPORATED,-78.97142,43.21616,03/22/2016,0,...,[],"[2.08314, 0.84081, 2.28417, 1.36245, 2.05507, ...",NaN,1.0,NaN,0.84081,NaN,0.4644,NaN,"[-78.96400638899155, 43.21088023895628]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14614,14614,14614,RAPANOS,SWL-2015-00176,Little Rock,Pine Bluff Arsenal: Building Demolition,-92.09857,34.32060,05/20/2016,0,...,[1.26976],"[2.1995, 2.24988, 1.12851, 1.71831, 1.65043, 1...",0.0,2.0,1.26976,1.12851,0.135,0.8316,"[-92.09210850004088, 34.3307138042913]","[-92.09799233523734, 34.33076202423372]"
14615,14615,14615,RAPANOS,SWL-2016-00403,Little Rock,City of Marshall - Waterline Replacement,-92.63156,35.90693,01/19/2018,0,...,[],"[1.27736, 1.04087, 1.47706]",NaN,1.0,NaN,1.04087,NaN,5.5170,NaN,"[-92.63946712914063, 35.900102466803624]"
14616,14616,14616,RAPANOS,SWT-2014-00848-rbh,Tulsa,Sofidel/AEP/Terracon Project 04147070-1 JD alo...,-95.55320,36.12439,01/30/2018,1,...,"[1.40828, 1.36894]",[2.45195],1.0,0.0,1.36894,2.45195,0.055,13.1337,"[-95.55933592285648, 36.11310191024127]","[-95.5603482061016, 36.14571290965774]"
14617,14617,14617,RAPANOS,SWT-2016-00539,Tulsa,"Proposed Walmart Development 45 acre site, NW ...",-97.58169,35.65544,11/17/2016,0,...,[],"[1.64757, 2.24442, 1.41223, 2.57258, 1.17818, ...",NaN,8.0,NaN,0.43727,NaN,0.7866,NaN,"[-97.58076374775679, 35.65157215755072]"
14618,14618,14618,RAPANOS,SWT-2017-00650,Tulsa,"North Fork Solar Project, LLC, Sec 21,22,27,28...",-98.98376,34.62336,05/07/2018,0,...,[1.44951],"[1.19179, 0.35953, 1.23638]",0.0,1.0,1.44951,0.35953,0.014,3.6135,"[-98.97695549214, 34.6351538500515]","[-98.98107367499516, 34.620999433833575]"

In [37]:
def square(lat=45.475649, lon=-69.471018, size=100):
  crs_proj = "EPSG:4326"  
  return ee.Geometry.Point([lon, lat], proj=crs_proj).buffer(size).bounds()


srtm = ee.Image('USGS/SRTMGL1_003')
# slope = ee.Terrain.slope(srtm)
# jrc = ee.Image("JRC/GSW1_2/GlobalSurfaceWater").select("seasonality", "recurrence")

def get_wb_elevation(x, patch_size=10):
    image = ee.Image('USGS/SRTMGL1_003')
    patch_size = 10
    try:
        lat = x.closest_wb_centroid_coord[1]
        lon = x.closest_wb_centroid_coord[0]
        mean = image.reduceRegion(
                reducer = ee.Reducer.mean(),
                geometry = square(lat, lon, patch_size),
                scale = 30,
                maxPixels = 1e9
            ).getInfo()

        return mean.get('elevation')

    except Exception as e:
#         print(e)
        return np.nan

    
def get_fl_elevation(x, patch_size=10):
    image = ee.Image('USGS/SRTMGL1_003')
    patch_size = 10
    try:
        lat = x.closest_fl_centroid_coord[1]
        lon = x.closest_fl_centroid_coord[0]
        mean = image.reduceRegion(
                reducer = ee.Reducer.mean(),
                geometry = square(lat, lon, patch_size),
                scale = 30,
                maxPixels = 1e9
            ).getInfo()

        return mean.get('elevation')

    except Exception as e:
#         print(e)
        return np.nan

In [38]:
# temp = df_centroid[0:30].copy()
# # temp
# temp.apply(lambda x: get_wb_elevation(x), axis=1)

# # df_centroid.apply(lambda x: get_stats(), axis=1)

In [39]:
# df_centroid["closest_wb_elevation"] = df_centroid.apply(lambda x: get_wb_elevation(x, patch_size=10), axis=1)
# df_centroid["closest_fl_elevation"] = df_centroid.apply(lambda x: get_fl_elevation(x, patch_size=10), axis=1)
# df_centroid.columns

# df_centroid = df_centroid[1:3].copy()

In [40]:
df_centroid.shape

(14619, 41)

In [41]:
from datetime import datetime
start = datetime.now()
print(datetime.now())

2021-03-23 11:44:02.451983

In [43]:
# pass in batches of 500
# MADHUKAR: 0 - 5000 
# SHOBHA: 5000 - 10000
# RADHIKA: 10000 - 15000

patch_size = 10
batch_size = 500
MY_NAME = "MADHUKAR"
START = 0 + 5000 * (MY_NAME == "SHOBHA") + 10000 * (MY_NAME == "RADHIKA")

for batch in range(10):
  print("batch {} of 10 started".format(batch + 1))
  batch_df = df_centroid[START + batch_size * batch : START + batch_size * (batch + 1)].copy()
  batch_df["closest_wb_elevation"] = batch_df.apply(lambda x: get_wb_elevation(x, patch_size), axis=1)
  batch_df["closest_fl_elevation"] = batch_df.apply(lambda x: get_fl_elevation(x, patch_size), axis=1)
  print("batch {} of 10 done".format(batch + 1))
  i = (START + batch_size * batch) + 1
  (pickle.dump(batch_df, open("nearest_wb_fl_elevation/nearest_wb_fl_elevation"
                           + "_part" + str(i),"wb"), 
               protocol=3))

batch 1 of 10 started
batch 1 of 10 done
batch 2 of 10 started
batch 2 of 10 done
batch 3 of 10 started
batch 3 of 10 done
batch 4 of 10 started
batch 4 of 10 done
batch 5 of 10 started
batch 5 of 10 done
batch 6 of 10 started
batch 6 of 10 done
batch 7 of 10 started
batch 7 of 10 done
batch 8 of 10 started
batch 8 of 10 done
batch 9 of 10 started
batch 9 of 10 done
batch 10 of 10 started
batch 10 of 10 done

In [44]:
end = datetime.now()
delta = end-start
print(delta.seconds/60)

20.133333333333333

In [45]:
# pass in batches of 500
# MADHUKAR: 0 - 5000 
# SHOBHA: 5000 - 10000
# RADHIKA: 10000 - 15000

patch_size = 10
batch_size = 500
MY_NAME = "SHOBHA"
START = 0 + 5000 * (MY_NAME == "SHOBHA") + 10000 * (MY_NAME == "RADHIKA")

for batch in range(10):
  print("batch {} of 10 started".format(batch + 1))
  batch_df = df_centroid[START + batch_size * batch : START + batch_size * (batch + 1)].copy()
  batch_df["closest_wb_elevation"] = batch_df.apply(lambda x: get_wb_elevation(x, patch_size), axis=1)
  batch_df["closest_fl_elevation"] = batch_df.apply(lambda x: get_fl_elevation(x, patch_size), axis=1)
  print("batch {} of 10 done".format(batch + 1))
  i = (START + batch_size * batch) + 1
  (pickle.dump(batch_df, open("nearest_wb_fl_elevation/nearest_wb_fl_elevation"
                           + "_part" + str(i),"wb"), 
               protocol=3))

batch 1 of 10 started
batch 1 of 10 done
batch 2 of 10 started
batch 2 of 10 done
batch 3 of 10 started
batch 3 of 10 done
batch 4 of 10 started
batch 4 of 10 done
batch 5 of 10 started
batch 5 of 10 done
batch 6 of 10 started
batch 6 of 10 done
batch 7 of 10 started
batch 7 of 10 done
batch 8 of 10 started
batch 8 of 10 done
batch 9 of 10 started
batch 9 of 10 done
batch 10 of 10 started
batch 10 of 10 done

In [46]:
patch_size = 10
batch_size = 500
MY_NAME = "RADHIKA"
START = 0 + 5000 * (MY_NAME == "SHOBHA") + 10000 * (MY_NAME == "RADHIKA")

for batch in range(10):
  print("batch {} of 10 started".format(batch + 1))
  batch_df = df_centroid[START + batch_size * batch : START + batch_size * (batch + 1)].copy()
  batch_df["closest_wb_elevation"] = batch_df.apply(lambda x: get_wb_elevation(x, patch_size), axis=1)
  batch_df["closest_fl_elevation"] = batch_df.apply(lambda x: get_fl_elevation(x, patch_size), axis=1)
  print("batch {} of 10 done".format(batch + 1))
  i = (START + batch_size * batch) + 1
  (pickle.dump(batch_df, open("nearest_wb_fl_elevation/nearest_wb_fl_elevation"
                           + "_part" + str(i),"wb"), 
               protocol=3))

batch 1 of 10 started
batch 1 of 10 done
batch 2 of 10 started
batch 2 of 10 done
batch 3 of 10 started
batch 3 of 10 done
batch 4 of 10 started
batch 4 of 10 done
batch 5 of 10 started
batch 5 of 10 done
batch 6 of 10 started
batch 6 of 10 done
batch 7 of 10 started
batch 7 of 10 done
batch 8 of 10 started
batch 8 of 10 done
batch 9 of 10 started
batch 9 of 10 done
batch 10 of 10 started
batch 10 of 10 done

In [47]:
df = pd.read_pickle("nearest_wb_fl_elevation/nearest_wb_fl_elevation_part1")
# df.closest_fl_elevation
df.head()

,Unnamed: 0,Unnamed: 0.1,jurisdiction_type,da_number,district,project_name,longitude,latitude,date_issued_or_denied,rha_determination,...,wb_min_index,fl_min_index,closest_wb_distance_m,closest_fl_distance_m,closest_wb_area_sqkm,closest_fl_area_sqkm,closest_wb_centroid_coord,closest_fl_centroid_coord,closest_wb_elevation,closest_fl_elevation
0,0,0,RAPANOS,LRB-1983-10120,Buffalo,Trade-A-Yacht (Hibiscus Harbor - Union Springs...,-76.70773,42.85821,06/19/2020,0,...,1.0,3.0,0.19900,1.55869,0.006,0.1170,"[-76.70555483355493, 42.857404962517336]","[-76.72068711614911, 42.847915233402816]",434.326797,114.000000
1,1,1,RAPANOS,LRB-1985-69031,Buffalo,"POOLEY, MARK A.",-75.85524,43.15230,07/07/2016,0,...,0.0,3.0,7.21302,0.48290,207.005,1.4841,"[-75.90992647216409, 43.20342341684462]","[-75.8611681181417, 43.15253659471059]",112.000000,112.000000
2,2,2,RAPANOS,LRB-1986-99614,Buffalo,"Bellamy, Michael (previous: MACKO, JOHN)",-78.04046,42.68911,10/12/2017,0,...,0.0,4.0,0.82916,0.47677,3.329,1.1124,"[-78.03287556981176, 42.694050497478464]","[-78.03825316195692, 42.68513894536421]",413.000000,413.000000
3,3,3,RAPANOS,LRB-1990-97632,Buffalo,WESTWOOD COUNTRY CLUB,-78.77134,42.97994,06/28/2016,0,...,1.0,0.0,0.78709,1.04919,0.004,13.9392,"[-78.77438291804144, 42.986663531552246]","[-78.75975051198779, 42.984037710099216]",187.210526,188.535948
4,4,4,RAPANOS,LRB-1991-98611,Buffalo,MODERN LANDFILL INCORPORATED,-78.97142,43.21616,03/22/2016,0,...,NaN,1.0,NaN,0.84081,NaN,0.4644,NaN,"[-78.96400638899155, 43.21088023895628]",NaN,98.506494