In [1]:
import sys
print(sys.executable)
print(sys.version)
print(sys.version_info)

/Users/Madhukar/opt/miniconda3/envs/ee_skmr/bin/python
3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)
[Clang 11.0.1 ]
sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)

In [2]:
import ee
import pandas as pd
import numpy as np
ee.Initialize()

In [3]:
# read in the nhd addendum file
nhd_stats = pd.read_csv("nhd_stats_AI.csv")

# read in csv file with SSURGO variables
df_m = pd.read_csv("combined_regular_clean_with_ssurgo_variables.csv")

In [4]:
# comid's from GEE are extracted into several pickled files
# pickling is needed to be able to share easily across team members 
# join these pickled files into one full dataset

df_merged_full = []

for i in range(df_m.shape[0] // 500 + 1):
    try:
        df_temp = pd.read_pickle(('NHD_extracted_vars_2.5kmX2.5km/combined_regular_clean_with_ssurgo_nhd_variables_part' + 
                              str(500 * i + 1)))
    except:
        break
    df_merged_full.append(df_temp)
df_merged_full = pd.concat(df_merged_full)

In [5]:
df_merged_full.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'Index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb', 'nhd_vars_fl'],
      dtype='object')

# A word on 'nhd_vars_wb' and 'nhd_vars_fl' columns (see last two columns above)

## nhd_vars_wb: this is a list of lists
- for each record, the following six features from GEE are extracted as lists and stored into a list
- [comid_list, ftype_str, gnis_id, wb_area, fl_length, fcode]
- the column is labeled nhd_vars_wb for waterbodies

In a similar fashion, there is another column for flowlines labeled nhd_vars_fl

Note: fl_length is NaN's for waterbodies and wb_area ae NaN's for flowlines

## In the following, features are extracted from the above columns and feature engineered as discussed in meetings. Pls use your judgement to help devise any new features you wish

In [6]:
# wb for waterbodies
# extract the individual lists
df_merged_full["wb_comid_list"] = df_merged_full.apply(lambda x: x.nhd_vars_wb[0], axis=1)
df_merged_full["wb_ftype_str_list"] = df_merged_full.apply(lambda x: x.nhd_vars_wb[1], axis=1)
df_merged_full["wb_gnis_id_list"] = df_merged_full.apply(lambda x: x.nhd_vars_wb[2], axis=1)
df_merged_full["wb_area_list"] = df_merged_full.apply(lambda x: x.nhd_vars_wb[3], axis=1)

# fl for flowlines
# extract the individual lists
df_merged_full["fl_comid_list"] = df_merged_full.apply(lambda x: x.nhd_vars_fl[0], axis=1)
df_merged_full["fl_ftype_str_list"] = df_merged_full.apply(lambda x: x.nhd_vars_fl[1], axis=1)
df_merged_full["fl_gnis_id_list"] = df_merged_full.apply(lambda x: x.nhd_vars_fl[2], axis=1)
df_merged_full["fl_length_list"] = df_merged_full.apply(lambda x: x.nhd_vars_fl[4], axis=1)

# Lets look at columns of interest

In [7]:
df_merged_full[df_merged_full.columns[29:39]][9:15]

,nhd_vars_wb,nhd_vars_fl,wb_comid_list,wb_ftype_str_list,wb_gnis_id_list,wb_area_list,fl_comid_list,fl_ftype_str_list,fl_gnis_id_list,fl_length_list
9,"([120052831, 22027044], [None, None], [974076,...","([21980197, 21980245, 21980217, 21980207, 2198...","[120052831, 22027044]","[None, None]","[974076, ]","[171.202, 0.008]","[21980197, 21980245, 21980217, 21980207, 21980...","[None, None, None, None, None, None, None, Non...","[, , , , , , , , 973757, , 974058]","[0.022, 1.975, 3.135, 0.725, 2.786, 0.764, 3.0..."
10,"([904140245], [None], [1075813], [12045.529], ...","([15594559, 15594563, 15594573, 15594565, 1559...",[904140245],[None],[1075813],[12045.529],"[15594559, 15594563, 15594573, 15594565, 15594...","[None, None, None, None, None, None, None, None]","[, , 1066928, 1066928, 1066928, , , 1066928]","[0.602, 0.217, 1.254, 0.208, 7.518, 5.608, 12...."
11,"([21631197, 904140246, 21631201], [None, None,...","([21632385, 21632387, 21632389, 21635915, 2163...","[21631197, 904140246, 21631201]","[None, None, None]","[967326, 970427, ]","[0.425, 6693.837, 0.946]","[21632385, 21632387, 21632389, 21635915, 21635...","[None, None, None, None, None, None, None, None]","[, , , , , , , ]","[2.781, 0.287, 1.895, 0.871, 10.109, 0.15, 1.1..."
12,"([15586156, 15586164], [None, None], [1078482,...","([15588640, 15588636, 15587674, 15587680, 1558...","[15586156, 15586164]","[None, None]","[1078482, 1079552]","[0.139, 0.051]","[15588640, 15588636, 15587674, 15587680, 15587...","[None, None, None, None, None, None, None]","[, , , , 1066599, 1066599, 1066851]","[0.941, 0.658, 1.216, 0.505, 0.968, 3.143, 1.98]"
13,"([], [], [], [], [], [])","([15560355, 15560297, 15560169, 15560311, 1556...",[],[],[],[],"[15560355, 15560297, 15560169, 15560311, 15560...","[None, None, None, None, None, None, None, Non...","[968024, 968024, , , , , , , ]","[0.766, 4.526, 1.44, 1.941, 0.95, 0.641, 0.372..."
14,"([], [], [], [], [], [])","([15594581, 15594569, 15594591], [None, None, ...",[],[],[],[],"[15594581, 15594569, 15594591]","[None, None, None]","[, 1044708, 1044708]","[1.943, 2.539, 4.12]"

## Lets look at one row in individual columns

In [8]:
# looking at waterbodies list
df_merged_full.nhd_vars_wb[9]
# you can see there are 6 items in the list [comid_list, ftype_str, gnis_id, wb_area, fl_length, fcode]
# note that fcode is going to be null due to coding lapse

([120052831, 22027044],
 [None, None],
 ['974076', ''],
 [171.202, 0.008],
 [nan, nan],
 [])

In [9]:
# looking at flowlines list
df_merged_full.nhd_vars_fl[9]

([21980197,
  21980245,
  21980217,
  21980207,
  21980203,
  21980199,
  21980195,
  21980193,
  21978319,
  21978365,
  21978323],
 [None, None, None, None, None, None, None, None, None, None, None],
 ['', '', '', '', '', '', '', '', '973757', '', '974058'],
 [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
 [0.022, 1.975, 3.135, 0.725, 2.786, 0.764, 3.016, 1.652, 3.419, 3.557, 2.136],
 [])

In [10]:
# list of comids in waterbodies
df_merged_full.wb_comid_list[9]

[120052831, 22027044]

In [11]:
# list of comids in flowlines
df_merged_full.fl_comid_list[9]

[21980197,
 21980245,
 21980217,
 21980207,
 21980203,
 21980199,
 21980195,
 21980193,
 21978319,
 21978365,
 21978323]

### .... and so on

In [12]:
# ### Filter out invalid comids (although not used in this notebook)
# # "invalid" = present in GEE but not present in nhd_stats

# df_merged["wb_comid_list_filtered"] = df_merged.apply(lambda x: [comid for comid in x.nhd_vars_wb[0] if comid in np.array(nhd_stats.comid)
#                                                                 ], axis=1)

# df_merged["fl_comid_list_filtered"] = df_merged.apply(lambda x: [comid for comid in x.nhd_vars_fl[0] if comid in np.array(nhd_stats.comid)
#                                                                 ], axis=1)

In [13]:
# Assigned begin and end of records for each person
# MADHUKAR: records 1 - 5000
# SHOBHA: records 5000 - 10000
# RADHIKA: records 10000 - 15000

In [14]:
# Extract features present in nhd_stats for corresponding comid
# read in fl_comid_list, pull out matching variable values in nhd_stats

df_merged = df_merged_full

def extract_feature(comid, feature):
    """
    Extract features present in nhd_stats for corresponding comid
    """
    if comid == None:
        return np.nan # if no comid's in GEE
    extracted_feature = nhd_stats[nhd_stats["comid"] == comid][str(feature)]
    try:
        extracted_feature = np.array(extracted_feature).item() 
    except Exception as e:
        return np.nan # if comid in GEE but not in nhd database
    return extracted_feature


def extract_sum(feature):
    """
    feature engineering per excel sheet
    """
    return (df_merged.apply(lambda x: np.sum(np.array([extract_feature(comid, str(feature))
                                                                 for comid in x.fl_comid_list])
                                                       [~np.isnan(np.array([extract_feature(comid, str(feature))
                                                                            for comid in x.fl_comid_list]))]), 
                                                axis=1))
def extract_count(feature):
    """
    feature engineering per excel sheet
    """
    return (df_merged.apply(lambda x: len(np.array([extract_feature(comid, str(feature))
                                                                 for comid in x.fl_comid_list])
                                                       [~np.isnan(np.array([extract_feature(comid, str(feature))
                                                                            for comid in x.fl_comid_list]))]), 
                                                  axis=1))

In [15]:
# flowline variables

# areasqkm
df_merged["fl_areasqkm_sum"] = extract_sum("areasqkm")
df_merged["fl_areasqkm_count"] = extract_count("areasqkm")
df_merged["fl_areasqkm_mean"] = (df_merged.apply(lambda x: 
                                                 (x.fl_areasqkm_sum/x.fl_areasqkm_count) 
                                                 if x.fl_areasqkm_count != 0 
                                                 else np.nan, axis=1))

# gnis_name_ind
df_merged["fl_gnis_name_ind_sum"] = extract_sum("gnis_name_ind")
df_merged["fl_gnis_name_ind_count"] = extract_count("gnis_name_ind")
df_merged["fl_gnis_name_ind_mean"] = (df_merged.apply(lambda x: 
                                                 (x.fl_gnis_name_ind_sum/x.fl_gnis_name_ind_count) 
                                                 if x.fl_areasqkm_count != 0 
                                                 else np.nan, axis=1))

# totdasqkm
df_merged["fl_totdasqkm_sum"] = extract_sum("totdasqkm")
df_merged["fl_totdasqkm_count"] = extract_count("totdasqkm")
df_merged["fl_totdasqkm_mean"] = (df_merged.apply(lambda x: 
                                                 (x.fl_totdasqkm_sum/x.fl_totdasqkm_count) 
                                                 if x.fl_areasqkm_count != 0 
                                                 else np.nan, axis=1))

# flow_type
df_merged["fl_flow_type_sum"] = extract_sum("flow_type")
df_merged["fl_flow_type_count"] = extract_count("flow_type")
df_merged["fl_flow_type_mean"] = (df_merged.apply(lambda x: 
                                                 (x.fl_flow_type_sum/x.fl_flow_type_count) 
                                                 if x.fl_areasqkm_count != 0 
                                                 else np.nan, axis=1))

# streamorde
df_merged["fl_streamorde_sum"] = extract_sum("streamorde")
df_merged["fl_streamorde_count"] = extract_count("streamorde")
df_merged["fl_streamorde_mean"] = (df_merged.apply(lambda x: 
                                                 (x.fl_streamorde_sum/x.fl_streamorde_count) 
                                                 if x.fl_areasqkm_count != 0 
                                                 else np.nan, axis=1))

# intephem
df_merged["fl_intephem_sum"] = extract_sum("intephem")
df_merged["fl_intephem_count"] = extract_count("intephem")
df_merged["fl_intephem_mean"] = (df_merged.apply(lambda x: 
                                                 (x.fl_intephem_sum/x.fl_intephem_count) 
                                                 if x.fl_areasqkm_count != 0 
                                                 else np.nan, axis=1))

# startflag
df_merged["fl_startflag_sum"] = extract_sum("startflag")
df_merged["fl_startflag_count"] = extract_count("startflag")
df_merged["fl_startflag_mean"] = (df_merged.apply(lambda x: 
                                                 (x.fl_startflag_sum/x.fl_startflag_count) 
                                                 if x.fl_areasqkm_count != 0 
                                                 else np.nan, axis=1))

# divergence
df_merged["fl_divergence_sum"] = extract_sum("divergence")
df_merged["fl_divergence_count"] = extract_count("divergence")
df_merged["fl_divergence_mean"] = (df_merged.apply(lambda x: 
                                                 (x.fl_divergence_sum/x.fl_divergence_count) 
                                                 if x.fl_areasqkm_count != 0 
                                                 else np.nan, axis=1))

KeyboardInterrupt:

In [ ]:
# waterbodies variables

In [ ]:
# to do

# fcode

# In a similar fasion, you can feature engineer the waterbodies (I will get that later today/tomorrow and push the updated dataframe)

In [ ]:
df_merged.describe()

In [ ]:
# These are the variables that needs to be made accessible to manipulation via csv files
# wb_ftype_str_list
# wb_area_list
# fl_ftype_str_list
# fl_length_list

In [25]:
"fl_length" in df.columns

False

In [60]:
# wb for waterbodies
# extract the individual lists
df["wb_comid"] = df.apply(lambda x: "+".join([str(comid) for comid in x.nhd_vars_wb[0]]), axis=1)
df["wb_ftype_str"] = df.apply(lambda x: "+".join([str(ftype) for ftype in x.nhd_vars_wb[1] if ftype != None]), axis=1)
# df["wb_gnis_id"] = df.apply(lambda x: "+".join([str(gnis) for gnis in x.nhd_vars_wb[2]]), axis=1)

# # sum and mean
df["wb_area_sum"] = df.apply(lambda x: np.sum(np.array([area for area in x.nhd_vars_wb[3] if area != None])), axis=1)
df["wb_area_count"] = df.apply(lambda x: len([area for area in x.nhd_vars_wb[3] if area != None]), axis=1)
df["wb_area_mean"] = df.apply(lambda x: (x.wb_area_sum / x.wb_area_count) if x.wb_area_count != 0 else np.nan, axis=1)

df["wb_gnis_name_ind_sum"] = df.apply(lambda x: np.sum(np.array([int(gnis) for gnis in x.nhd_vars_wb[2] if gnis not in ["", None]])), axis=1)
df["wb_gnis_name_ind_count"] = df.apply(lambda x: len([gnis for gnis in x.nhd_vars_wb[2] if gnis not in ["", None]]), axis=1)
df["wb_gnis_name_ind_mean"] = df.apply(lambda x: (x.wb_gnis_name_ind_sum / x.wb_gnis_name_ind_count) if x.wb_gnis_name_ind_count != 0 else np.nan, axis=1)


# # fl for flowlines
# # extract the individual lists
df["fl_comid"] = df.apply(lambda x: "+".join([str(comid) for comid in x.nhd_vars_fl[0]]), axis=1)
df["fl_ftype_str"] = df.apply(lambda x: "+".join([str(ftype) for ftype in x.nhd_vars_fl[1]]), axis=1)
df["fl_gnis_id"] = df.apply(lambda x: "+".join(x.nhd_vars_fl[2]), axis=1)

# # sum and mean
df["fl_length_sum"] = df.apply(lambda x: np.sum(np.array([length for length in x.nhd_vars_wb[4] if length != None])), axis=1)
df["fl_length_count"] = df.apply(lambda x: len([length for length in x.nhd_vars_wb[4] if length != None]), axis=1)
df["fl_length_mean"] = df.apply(lambda x: (x.fl_length_sum / x.fl_length_count) if x.fl_length_count != 0 else np.nan, axis=1)

In [57]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'Index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb', 'nhd_vars_fl',
       'wb_comid_list', 'wb_ftype_str_list', 'wb_gnis_id_list', 'wb_area_list',
       'fl_comid_list', 'fl_ftype_str_list', 'fl_gnis_id_list',
       'fl_length_list', 'fl_areasqkm_sum', 'fl_areasqkm_count',
       'fl_areasqkm_mean', 'fl_gnis_name_ind_sum', 'fl_gnis_name_ind_count',
       'fl_gnis_name_ind_mean', 'fl_totdasqkm_sum', 'fl_totdasqkm_count',
       'fl_totdasqkm_mean', 'fl_flow_type_sum', 'fl_flow_type_count',
       'fl_flow_type_mean', 'fl_streamorde_sum', 'fl_streamorde_count',
       'fl_streamorde_mean', 'fl_intephem_sum', 'fl_intephem_count',
       'fl_intephem_mean', 'fl_startflag_sum', 'fl_startflag_count',
       'fl_startflag_mean', 'fl_divergence_sum', 'fl_divergence_count',
       'fl_divergence_mean', 'wb_comid', 'wb_ftype_str', 'wb_gnis_id',
       'wb_area_count', 'wb_area_sum', 'wb_area_mean', 'fl_length_sum',
       'fl_length_count', 'fl_length_mean', 'fl_comid', 'fl_ftype_str',
       'wb_gnis_name_ind_sum', 'fl_gnis_id', 'wb_gnis_name_ind_count',
       'wb_gnis_name_ind_mean'],
      dtype='object')

In [87]:
# df_merged.to_pickle("combined_regular_with_ssurgo_nhd_2.5kmX2.5km")

In [56]:
# df.to_csv("combined_regular_with_ssurgo_nhd_2.5kmX2.5km.csv")
# df.to_pickle("combined_regular_with_ssurgo_nhd_2.5kmX2.5km")

In [61]:
# df.to_csv("combined_regular_with_ssurgo_nhd_200mX200m.csv")
# df.to_pickle("combined_regular_with_ssurgo_nhd_200mX200m")

# This is where you would start

## 2.5km x 2.5km

In [11]:
df = pd.read_pickle("combined_regular_with_ssurgo_nhd_2.5kmX2.5km")
df.describe()

,Unnamed: 0,Unnamed: 0.1,longitude,latitude,rha_determination,cwa_determination,rha1,rha2,cwa1,cwa2,...,fl_divergence_mean,wb_area_count,wb_area_sum,wb_area_mean,fl_length_sum,fl_length_count,fl_length_mean,wb_gnis_name_ind_sum,wb_gnis_name_ind_count,wb_gnis_name_ind_mean
count,14500.000000,14500.000000,14500.000000,14500.000000,14500.000000,14500.000000,14500.000000,14500.000000,14500.000000,14500.000000,...,12235.000000,14500.000000,14500.000000,4789.000000,6851.0,14500.000000,0.0,1.450000e+04,14500.000000,2.204000e+03
mean,7249.500000,7249.500000,-90.471888,37.246073,0.104276,0.367448,0.070483,0.062000,0.092552,0.062828,...,6.415601,0.864690,241.770332,531.287553,0.0,1.341793,NaN,1.890623e+05,0.196828,9.841725e+05
std,4185.933787,4185.933787,15.441037,6.773079,0.305629,0.482127,0.255968,0.241164,0.289813,0.242661,...,11.386980,1.845366,3197.569053,4420.418133,0.0,2.036464,NaN,5.656384e+05,0.537846,4.793839e+05
min,0.000000,0.000000,-174.197880,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.002000,0.0,0.000000,NaN,0.000000e+00,0.000000,1.823000e+03
25%,3624.750000,3624.750000,-93.591248,32.825882,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.972125,0.000000,0.000000,0.031000,0.0,0.000000,NaN,0.000000e+00,0.000000,5.596909e+05
50%,7249.500000,7249.500000,-88.171130,35.504655,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.366720,0.000000,0.000000,0.112500,0.0,1.000000,NaN,0.000000e+00,0.000000,9.993760e+05
75%,10874.250000,10874.250000,-80.223938,41.431157,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,6.569775,1.000000,0.051000,1.550000,0.0,2.000000,NaN,0.000000e+00,0.000000,1.340351e+06
max,14499.000000,14499.000000,144.828420,70.483790,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,271.825200,26.000000,57535.316000,57516.647000,0.0,26.000000,NaN,1.148393e+07,7.000000,2.036537e+06

In [69]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'Index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb', 'nhd_vars_fl',
       'wb_comid_list', 'wb_ftype_str_list', 'wb_gnis_id_list', 'wb_area_list',
       'fl_comid_list', 'fl_ftype_str_list', 'fl_gnis_id_list',
       'fl_length_list', 'fl_areasqkm_sum', 'fl_areasqkm_count',
       'fl_areasqkm_mean', 'fl_gnis_name_ind_sum', 'fl_gnis_name_ind_count',
       'fl_gnis_name_ind_mean', 'fl_totdasqkm_sum', 'fl_totdasqkm_count',
       'fl_totdasqkm_mean', 'fl_flow_type_sum', 'fl_flow_type_count',
       'fl_flow_type_mean', 'fl_streamorde_sum', 'fl_streamorde_count',
       'fl_streamorde_mean', 'fl_intephem_sum', 'fl_intephem_count',
       'fl_intephem_mean', 'fl_startflag_sum', 'fl_startflag_count',
       'fl_startflag_mean', 'fl_divergence_sum', 'fl_divergence_count',
       'fl_divergence_mean', 'wb_comid', 'wb_ftype_str', 'wb_gnis_id',
       'wb_area_count', 'wb_area_sum', 'wb_area_mean', 'fl_length_sum',
       'fl_length_count', 'fl_length_mean', 'fl_comid', 'fl_ftype_str',
       'wb_gnis_name_ind_sum', 'fl_gnis_id', 'wb_gnis_name_ind_count',
       'wb_gnis_name_ind_mean'],
      dtype='object')

In [85]:
df.apply(lambda x: x.nhd_vars_wb[5], axis=1)

0        []
1        []
2        []
3        []
4        []
         ..
14495    []
14496    []
14497    []
14498    []
14499    []
Length: 14500, dtype: object

## 200m X 200m

In [6]:
df = pd.read_pickle("combined_regular_with_ssurgo_nhd_200mX200m")

In [62]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'Index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb', 'nhd_vars_fl',
       'wb_comid_list', 'wb_ftype_str_list', 'wb_gnis_id_list', 'wb_area_list',
       'fl_comid_list', 'fl_ftype_str_list', 'fl_gnis_id_list',
       'fl_length_list', 'fl_areasqkm_sum', 'fl_areasqkm_count',
       'fl_areasqkm_mean', 'fl_gnis_name_ind_sum', 'fl_gnis_name_ind_count',
       'fl_gnis_name_ind_mean', 'fl_totdasqkm_sum', 'fl_totdasqkm_count',
       'fl_totdasqkm_mean', 'fl_flow_type_sum', 'fl_flow_type_count',
       'fl_flow_type_mean', 'fl_streamorde_sum', 'fl_streamorde_count',
       'fl_streamorde_mean', 'fl_intephem_sum', 'fl_intephem_count',
       'fl_intephem_mean', 'fl_startflag_sum', 'fl_startflag_count',
       'fl_startflag_mean', 'fl_divergence_sum', 'fl_divergence_count',
       'fl_divergence_mean', 'wb_comid', 'wb_ftype_str', 'wb_area_sum',
       'wb_area_count', 'wb_area_mean', 'wb_gnis_name_ind_sum',
       'wb_gnis_name_ind_count', 'wb_gnis_name_ind_mean', 'fl_comid',
       'fl_ftype_str', 'fl_gnis_id', 'fl_length_sum', 'fl_length_count',
       'fl_length_mean'],
      dtype='object')

In [3]:
import pickle

In [5]:
pickle.HIGHEST_PROTOCOL
pickle.DEFAULT_PROTOCOL

4

In [12]:
import pickle

# use protocol 3 for backwards compatibility with Python 3.6 on AWS
pickle.dump(df, open("combined_regular_with_ssurgo_nhd_2.5kmX2.5km_pkl3.pkl","wb"), protocol=3)

In [13]:

with open("combined_regular_with_ssurgo_nhd_2.5kmX2.5km_pkl3.pkl", "rb") as f:
    df_readfrompkl = pickle.load(f)

In [14]:
df_readfrompkl

,Unnamed: 0,Unnamed: 0.1,jurisdiction_type,da_number,district,project_name,longitude,latitude,date_issued_or_denied,rha_determination,...,wb_area_mean,fl_length_sum,fl_length_count,fl_length_mean,fl_comid,fl_ftype_str,wb_gnis_name_ind_sum,fl_gnis_id,wb_gnis_name_ind_count,wb_gnis_name_ind_mean
0,0,0,RAPANOS,LRB-1983-10120,Buffalo,Trade-A-Yacht (Hibiscus Harbor - Union Springs...,-76.70773,42.85821,06/19/2020,0,...,NaN,NaN,2,NaN,21979931+21979911+21979905+21979901+21979897+2...,None+None+None+None+None+None,949513.0,+++++,1,949513.0
1,1,1,RAPANOS,LRB-1985-69031,Buffalo,"POOLEY, MARK A.",-75.85524,43.15230,07/07/2016,0,...,207.0050,NaN,1,NaN,22023626+22023590+22024934+22024936+22024940,None+None+None+None+None,959369.0,969955++++,1,959369.0
2,2,2,RAPANOS,LRB-1986-99614,Buffalo,"Bellamy, Michael (previous: MACKO, JOHN)",-78.04046,42.68911,10/12/2017,0,...,3.3290,NaN,1,NaN,15549029+15549021+15549673+15549671+15549667+1...,None+None+None+None+None+None+None,965260.0,++++++,1,965260.0
3,3,3,RAPANOS,LRB-1990-97632,Buffalo,WESTWOOD COUNTRY CLUB,-78.77134,42.97994,06/28/2016,0,...,0.0045,NaN,2,NaN,15569727+15568933,None+None,0.0,949513+,0,NaN
4,4,4,RAPANOS,LRB-1991-98611,Buffalo,MODERN LANDFILL INCORPORATED,-78.97142,43.21616,03/22/2016,0,...,NaN,0.0,0,NaN,15560517+15560355+15560297+15560311+15560505+1...,None+None+None+None+None+None+None,0.0,968024+968024+968024++++,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14495,14495,14495,RAPANOS,SAC-2018-00544,Charleston,Hawthorne Landing (fka Liberty Village Phases ...,-80.00178,33.01856,09/20/2018,0,...,NaN,NaN,4,NaN,9643633+9643661+9642689,None+None+None,2450902.0,1250249+1250249+1250249,2,1225451.0
14496,14496,14496,NWPR,SAC-2018-00746,Charleston,"OKR, LLC Tracts 1&2",-79.03356,33.56963,11/12/2020,0,...,NaN,NaN,8,NaN,11564490+9071180+9071192,None+None+None,0.0,++,0,NaN
14497,14497,14497,RAPANOS,SAC-2018-01470,Charleston,SCDOT US 76 interchange with US 601 in Richlan...,-80.68629,33.94163,03/24/2020,0,...,NaN,NaN,2,NaN,9679056+9679114+9681706+9719991+9719961+9681704,None+None+None+None+None+None,0.0,1222909+1222909+1222909+++1222909,0,NaN
14498,14498,14498,RAPANOS,SAC-2018-01892,Charleston,Old Bulah Plantation-Sandridge Rd,-80.42819,33.11993,08/06/2019,0,...,NaN,0.0,0,NaN,9609576+9609192,None+None,0.0,1222982+1221672,0,NaN
14499,14499,14499,RAPANOS,SAC-2019-00147,Charleston,Gray Storage Project,-81.07115,32.29055,03/04/2020,0,...,NaN,NaN,1,NaN,,,1222520.0,,1,1222520.0